### PR TITLE
fix(data-products): null-safety in change-impact analyzer for products without team/description/support

### PR DESCRIPTION
**Pull request by mvkonchits-db**
## Summary

Found while debugging a customer 500 on `PUT /api/data-products/{id}` (adding an output port). **Not a regression from #318** — latent null-safety bug exposed by a permitted-but-undertested state: a data product with `owner_team_id IS NULL` and no row in `data_product_teams`. The response builder serializes that as `team: None`, and the change-impact analyzer crashes on `old_product.get('team', {}).get('members', [])`.

### The Python footgun

`dict.get('k', default)` only falls back to `default` when the key is **missing**. When the key is **present but the value is None**, the default is skipped and the chained `.get(...)` raises `AttributeError: 'NoneType' object has no attribute 'get'`. Confirmed in DB inspection of the affected deployment with team-less products — schema permits it (`owner_team_id` is nullable), the API returns the product fine, only the analyzer trips.

## Call sites fixed

In `src/backend/src/utils/product_change_analyzer.py`:

- `analyze()`: `team`, `description`, `support`, `inputPorts`, `outputPorts`, `managementPorts` — switched every `x.get('k', default)` (where the value can legitimately be `None`) to `x.get('k') or default`. The two-level `team → members` access uses `(x.get('team') or {}).get('members') or []`.
- `_analyze_port_changes()`: filter out `None` entries when building the port name → port map.
- `_analyze_team_changes()`: same defensive filter for member list, plus `or ''` on the name/email key fallback so a member with both fields `None` doesn't blow up the dict comprehension.
- `_analyze_support_changes()`: same defensive filter for support channel list.
- `role.lower()` calls now use `role = member.get('role') or 'unknown'` so a stored `role=None` doesn't crash.

## Regression test

New `src/backend/src/tests/unit/test_product_change_analyzer.py` covers:

1. All top-level optional fields = `None` (smoke test — analyzer returns a clean empty-change result, no raise).
2. `team: None` → populated team (analyzer recognizes a feature-level addition).
3. `team` present but `members: None` (second-level None path).
4. `outputPorts: None` → populated ports (feature-level).
5. `support: None` on both sides.
6. `description: None` on both sides.
7. Team member with `role=None` (covers `role.lower()` crash path).

All 7 cases pass; existing tests untouched.

## Ship plan

Small, isolated, no schema or API changes. Pure null-safety hardening in one utility module + a new unit test file.

### CODE REVIEW

**Review by larsgeorge-db — APPROVED** [review]
lgtm
